name = "healthsathi"
main = "./_worker.js"
compatibility_date = "2025-05-11"
compatibility_flags = ["nodejs_compat"]

# Configure for static site deployment
[site]
bucket = "./out"
site_include = ["**/*"]
site_exclude = []
entry-point = "./"

[[kv_namespaces]]
binding = "ASSETS"
preview_id = "ASSETS"
id = "ASSETS"

[build]
command = "npm run build" 