name = "healthsathi"
main = "./_worker.js"
compatibility_date = "2025-05-11"
compatibility_flags = ["nodejs_compat"]

# Configure for static site deployment
[site]
bucket = "./out"
site_include = ["**/*"]
site_exclude = []

[build]
command = "npm run build" 